title: markdown-to-web
description: "A project to create static websites using markdown files and GitHub Pages"
baseurl: ""
url: "https://fonij80.github.io/markdown-to-web"
theme: jekyll-theme-cayman

# Multilingual Setup
languages: ["en", "fa"] # Use 'languages' key as expected by the plugin
default_lang: "en"

# Plugins
plugins:
  - jekyll-multiple-languages-plugin

# Exclude files/folders from localization (optional, to avoid duplication)
exclude_from_localizations:
  - "README.fa.md"
  - "resume-templates/fa/"
  - "README.md"
  - "resume-templates/en/"

# Permalinks and language-specific settings can be handled via folder structure and front matter,
# so no need to specify 'en:' and 'fa:' keys here unless you have custom config per language.

# Other Jekyll Settings
markdown: kramdown
kramdown:
  input: GFM
